In [1]:
import numpy as np 
import torch

In [ ]:
def contextual_signal_generator()

In [12]:
def sigmoid(x):

    return 1.0 / (1+np.exp(-x))

In [7]:
# Simple linear regression
X = np.array([5,4,3,6,7,9,10,3,4]).reshape(-1, 1)
y = 5*X + 3
reg = LinearRegression().fit(X,y)
reg.score(X,y)
reg.coef_

array([[5.]])

In [2]:
# Multiple linear regression with two variables 
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.score(X,y)
reg.coef_

array([1., 2.])

In [21]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y_sig = sigmoid(np.dot(X, np.array([1, 2])) - 5)
print(y_sig)
reg = LogisticRegression().fit(X,y_sig)

[0.11920292 0.5        0.73105858 0.95257413]


ValueError: Unknown label type: 'continuous'